### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DavidBindloss** [DavidBindloss/mew#1]
- [ ] Add comments

- [ ] Flow diagram of new component

- [ ] Flow diagram of mounting a component

- [ ] Flow diagram of an update being rendered.

- [ ] jsDocs on all functions
